/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 ******************************************************************************

 */

//where is the led coneected
//Port: PC
//Pin: 0
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// ahb and apb bus peripheal base address
#define PERIPHERAL_BASE 		(0x40000000UL)
#define APB1PERIPH_OFFSET		(0x00000000UL)
#define APB1PERIPH_BASE			(PERIPHERAL_BASE+APB1PERIPH_OFFSET)
#define APB2PERIPH_OFFSET		(0x00010000UL)
#define APB2PERIPH_BASE			(PERIPHERAL_BASE+APB2PERIPH_OFFSET)
#define AHB1PERIPH_OFFSET		(0x00020000UL)
#define AHB1PERIPH_BASE			(PERIPHERAL_BASE+AHB1PERIPH_OFFSET)
#define AHB2PERIPH_OFFSET		(0x08000000UL)
#define AHB2PERIPH_BASE			(PERIPHERAL_BASE+AHB2PERIPH_OFFSET)


// gpio bus address
#define GPIOA_OFFSET			(0x00000000)
#define GPIOB_OFFSET			(0x00000400)
#define GPIOC_OFFSET			(0x00000800)
#define GPIOD_OFFSET			(0x00000C00)
#define GPIOE_OFFSET			(0x00001000)
#define GPIOF_OFFSET			(0x00001400)

#define GPIOA_BASEADDR			(AHB2PERIPH_BASE+GPIOA_OFFSET)
#define GPIOB_BASEADDR			(AHB2PERIPH_BASE+GPIOB_OFFSET)
#define GPIOC_BASEADDR			(AHB2PERIPH_BASE+GPIOC_OFFSET)
#define GPIOD_BASEADDR			(AHB2PERIPH_BASE+GPIOD_OFFSET)
#define GPIOE_BASEADDR			(AHB2PERIPH_BASE+GPIOE_OFFSET)
#define GPIOF_BASEADDR			(AHB2PERIPH_BASE+GPIOF_OFFSET)

#define RCC_OFFSET				(0x00001000)
#define RCC_BASEADDR			(AHB1PERIPH_BASE+RCC_OFFSET)

#define AHB1EN_R_OFFSET			(0x14UL)
#define RCC_AHB1EN_R			(*(volatile uint32_t *)(RCC_BASEADDR+AHB1EN_R_OFFSET))//address is a pointer of volatile uint32_t

#define GPIO_MODE_R_OFFSET		(0x00UL)
#define GPIOC_MODE_R			(*(volatile uint32_t *)(GPIOC_BASEADDR+GPIO_MODE_R_OFFSET))

#define GPIO_OD_R_OFFSET		(0x14UL)
#define GPIOC_OD_R				(*(volatile uint32_t *)(GPIOC_BASEADDR+GPIO_OD_R_OFFSET))

#define GPIOCEN					(1<<19)
#define PIN0					(1<<0)
#define LED_PIN					PIN0
int main(void)
{
	/* Loop forever */
	// 1. enable clock access to gpioc
	RCC_AHB1EN_R |= GPIOCEN;

	// 2.set PC0 as output pin
	GPIOC_MODE_R |= (1<<0);
	GPIOC_MODE_R &= ~(1<<1);

	while(1)
	{
		//3. set PC- high
		GPIOC_OD_R |= LED_PIN; //means *address =1<<0 // dereferencing address to store value

		for(uint16_t i=0;i<10000;i++){
			__asm("nop");
		}
		GPIOC_OD_R &= ~LED_PIN; //means *address =1<<0 // dereferencing address to store value
					for(uint16_t i=0;i<10000;i++){
								__asm("nop");
							}
	}
}
